# Generated by Django 3.1.14 on 2023-06-21 14:08
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('description', models.TextField(default='Покемон', verbose_name='детальное описание покемона')),
                ('appeared_at', models.DateTimeField(help_text='появится', verbose_name='время появления покемона')),
                ('disappeared_at', models.DateTimeField(help_text='пропадет', verbose_name='время исчезновения покемона')),
                ('level', models.IntegerField(help_text='уровень', verbose_name='уровень развития покемона')),
                ('health', models.IntegerField(help_text='здоровье', verbose_name='уровень здоровья покемона')),
                ('attack', models.IntegerField(help_text='атака', verbose_name='атака покемона')),
                ('defense', models.IntegerField(help_text='защита', verbose_name='защита покемона')),
                ('stamina', models.IntegerField(help_text='выносливость', verbose_name='выносливость покемона')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='наименование пакемона')),
                ('title_en', models.TextField(blank=True, verbose_name='наименование пакемона на английском')),
                ('title_jp', models.TextField(blank=True, verbose_name='наименование пакемона на японском')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='изображение пакемона')),
                ('pokemon_entities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokemon_entities.pokemonentity', verbose_name='сущность')),
            ],
        ),
    ]
