# Generated by Django 3.1.14 on 2023-06-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='coordinats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemonentity'),
        ),
    ]
