# Generated by Django 3.1.14 on 2023-06-28 10:45
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity_evolution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='evolution',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
