# Generated by Django 3.1.14 on 2023-06-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_coordinats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='coordinats',
            field=models.ForeignKey(default=58.11, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemonentity'),
            preserve_default=False,
        ),
    ]
