# Generated by Django 3.1.14 on 2023-06-29 06:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230628_1420'),
    ]

    operations = [
    ]
