# Generated by Django 3.1.14 on 2023-06-29 06:34
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230629_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_entities',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='покемон'),
        ),
    ]
